# Generated by Django 5.2.1 on 2025-06-02 17:58

import appkarin.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('codigo', models.CharField(default=appkarin.models.generate_denuncia_code, editable=False, help_text='Código único de seguimiento de la denuncia', max_length=11, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=2000)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado_actual', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En Revisión'), ('EN_INVESTIGACION', 'En Investigación'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado')], default='PENDIENTE', max_length=50)),
            ],
            options={
                'verbose_name': 'Denuncia',
                'verbose_name_plural': 'Denuncias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DenunciaEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Estado de la denuncia',
                'verbose_name_plural': 'Estados de las denuncias',
            },
        ),
        migrations.CreateModel(
            name='RelacionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Relacion_empresa',
                'verbose_name_plural': 'Relaciones_empresa',
            },
        ),
        migrations.CreateModel(
            name='Tiempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervalo', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Tiempo',
                'verbose_name_plural': 'Tiempos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.CharField(default=appkarin.models.generate_user_id, editable=False, help_text='ID único de 5 caracteres generado automáticamente', max_length=5, primary_key=True, serialize=False, unique=True)),
                ('anonimo', models.BooleanField(default=True, help_text='Si es True, solo se requiere el ID. Si es False, se requieren datos personales.')),
                ('rut', models.CharField(blank=True, help_text='RUT chileno (formato: 12345678-9 o 12.345.678-9)', max_length=12, null=True, unique=True, validators=[appkarin.models.validate_rut])),
                ('nombre', models.CharField(blank=True, help_text='Requerido para usuarios no anónimos', max_length=250, null=True)),
                ('apellidos', models.CharField(blank=True, help_text='Requerido para usuarios no anónimos', max_length=250, null=True)),
                ('correo', models.EmailField(blank=True, help_text='Requerido para usuarios no anónimos', max_length=250, null=True)),
                ('celular', models.CharField(blank=True, help_text='Número de celular chileno', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Formato: +56912345678 o 912345678', regex='^\\+?56?[0-9]{8,9}$')])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actividad', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appkarin.denuncia')),
            ],
            options={
                'verbose_name': 'archivo',
                'verbose_name_plural': 'archivos',
            },
        ),
        migrations.CreateModel(
            name='EstadosDenuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appkarin.denuncia')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appkarin.denunciaestado')),
            ],
            options={
                'verbose_name': 'Estado de denuncia',
                'verbose_name_plural': 'Estados de denuncias',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.CharField(max_length=500)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appkarin.categoria')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.AddField(
            model_name='denuncia',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appkarin.item'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='relacion_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appkarin.relacionempresa'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='tiempo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appkarin.tiempo'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appkarin.usuario'),
        ),
    ]
