# Generated by Django 5.2.1 on 2025-06-16 12:54

import appkarin.utils
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('codigo', models.CharField(default=appkarin.utils.generate_denuncia_code, editable=False, help_text='Código único de seguimiento de la denuncia', max_length=11, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=2000)),
                ('descripcion_relacion', models.CharField(blank=True, help_text="Descripción condicional a relacion empresa 'Otro' ", max_length=50, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado_actual', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En Revisión'), ('RESUELTO', 'Resuelto')], default='PENDIENTE', max_length=50)),
            ],
            options={
                'verbose_name': 'Denuncia',
                'verbose_name_plural': 'Denuncias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DenunciaEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Estado de la denuncia',
                'verbose_name_plural': 'Estados de las denuncias',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='nombre de la empresa asociada a Integra', max_length=250)),
                ('descripcion', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='RelacionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Relacion_empresa',
                'verbose_name_plural': 'Relaciones_empresa',
            },
        ),
        migrations.CreateModel(
            name='Tiempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervalo', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Tiempo',
                'verbose_name_plural': 'Tiempos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.CharField(default=appkarin.utils.generate_user_id, editable=False, help_text='ID único de 5 caracteres generado automáticamente', max_length=5, primary_key=True, serialize=False, unique=True)),
                ('anonimo', models.BooleanField(default=True, help_text='Si es True, solo se requiere el ID. Si es False, se requieren datos personales.')),
                ('rut', models.CharField(blank=True, help_text='RUT chileno (formato: 12345678-9 o 12.345.678-9)', max_length=12, null=True, unique=True, validators=[appkarin.utils.validate_rut])),
                ('nombre', models.CharField(blank=True, help_text='Requerido para usuarios no anónimos', max_length=250, null=True)),
                ('apellidos', models.CharField(blank=True, help_text='Requerido para usuarios no anónimos', max_length=250, null=True)),
                ('correo', models.EmailField(blank=True, help_text='Requerido para usuarios no anónimos', max_length=250, null=True)),
                ('celular', models.CharField(blank=True, help_text='Número de celular chileno', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Formato: +56912345678 o 912345678', regex='^\\+?56?[0-9]{8,9}$')])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actividad', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='AdminDenuncias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rut', models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[appkarin.utils.validate_rut])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('rol_categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appkarin.categoria')),
            ],
            options={
                'verbose_name': 'Administrador de Denuncias',
                'verbose_name_plural': 'Administradores de Denuncias',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('nombre', models.CharField(max_length=250)),
                ('descripción', models.CharField(max_length=250)),
                ('Peso', models.IntegerField(default=0, help_text='Peso del archivo en bytes')),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appkarin.denuncia')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
            },
        ),
        migrations.AddField(
            model_name='denuncia',
            name='tipo_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appkarin.empresa'),
        ),
        migrations.CreateModel(
            name='EstadosDenuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appkarin.denuncia')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appkarin.denunciaestado')),
            ],
            options={
                'verbose_name': 'Estado de denuncia',
                'verbose_name_plural': 'Estados de denuncias',
            },
        ),
        migrations.CreateModel(
            name='Foro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(max_length=2000)),
                ('leido', models.BooleanField(help_text='Boleano que indica si son mensajes obsoletos o no', null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, help_text='Administrador que escribió el mensaje (null si fue el usuario)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appkarin.denuncia')),
            ],
            options={
                'verbose_name': 'Foro',
                'verbose_name_plural': 'Foros',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.CharField(max_length=500)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appkarin.categoria')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.AddField(
            model_name='denuncia',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appkarin.item'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='relacion_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appkarin.relacionempresa'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='tiempo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appkarin.tiempo'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appkarin.usuario'),
        ),
    ]
