# Generated by Django 5.2.1 on 2025-11-06 13:03

import appkarin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appkarin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(blank=True, help_text='Archivo almacenado en DigitalOcean Spaces', max_length=500, null=True, upload_to=appkarin.models.archivo_upload_path),
        ),
        migrations.AddField(
            model_name='archivo',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='url',
            field=models.URLField(blank=True, help_text='URL del archivo (deprecado - usar archivo)', max_length=500),
        ),
    ]
