# Generated by Django 5.2.1 on 2025-06-09 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appkarin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindenuncias',
            name='rol_categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appkarin.categoria'),
        ),
    ]
