# Generated by Django 5.2.1 on 2025-06-13 19:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appkarin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foro',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foro',
            name='leido',
            field=models.BooleanField(help_text='Boleano que indica si son mensajes obsoletos o no', null=True),
        ),
    ]
