# Generated by Django 5.2.1 on 2025-06-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appkarin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='estado_actual',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En Revisión'), ('RESUELTO', 'Resuelto')], default='PENDIENTE', max_length=50),
        ),
    ]
