# Generated by Django 5.2.1 on 2025-06-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appkarin', '0002_alter_denuncia_estado_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='descripcion_relacion',
            field=models.CharField(blank=True, help_text="Descripción condicional a relacion empresa 'Otro' ", max_length=50, null=True),
        ),
    ]
