# Generated by Django 5.2.1 on 2025-06-04 20:56

import appkarin.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appkarin', '0003_denuncia_descripcion_relacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[appkarin.models.validate_rut])),
                ('nombre', models.CharField(max_length=250)),
                ('apellidos', models.CharField(max_length=250)),
                ('correo', models.EmailField(max_length=250, unique=True)),
                ('contraseña', models.CharField(max_length=250, validators=[appkarin.models.validate_admin_password])),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
            },
        ),
        migrations.AlterModelOptions(
            name='archivo',
            options={'verbose_name': 'Archivo', 'verbose_name_plural': 'Archivos'},
        ),
        migrations.CreateModel(
            name='Foro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(max_length=2000)),
                ('admin', models.ForeignKey(blank=True, help_text='Administrador que escribió el mensaje (null si fue el usuario)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appkarin.admin')),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appkarin.denuncia')),
            ],
            options={
                'verbose_name': 'Foro',
                'verbose_name_plural': 'Foros',
            },
        ),
    ]
